/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BondTypeEnum } from './bondTypeEnum';


/**
 * Representa un enlace evaluado para fragmentación. - idx: Índice del enlace en la molécula. - begin_atom: Índice del átomo inicial del enlace. - end_atom: Índice del átomo final del enlace. - bond_atoms: Representación legible del enlace (ejemplo: \'C-H\'). - is_fragmentable: Indica si el enlace puede fragmentarse (enlace simple, etc.).
 */
export interface EvaluatedFragmentBond { 
    idx: number;
    begin_atom: number;
    end_atom: number;
    bond_atoms: string;
    bond_type?: BondTypeEnum;
    is_fragmentable: boolean;
}
export namespace EvaluatedFragmentBond {
}


