/**
 * DeepBDE API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PredictedBond } from './predictedBond';

/**
 * Salida de /fragment/. - smiles_canonical: SMILES canónico de la molécula original - molecule_id: ID de la molécula - bonds_predicted: Lista de enlaces predichos - smiles_list: Lista de SMILES de los fragmentos (opcional) - xyz_block: Bloque XYZ de los fragmentos (opcional)
 */
export interface FragmentResponseData {
  smiles_canonical: string;
  molecule_id: string;
  bonds_predicted: Array<PredictedBond>;
  smiles_list?: Array<string> | null;
  xyz_block?: string | null;
}
