/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EvaluatedFragmentBond } from './evaluatedFragmentBond';


/**
 * Salida de /fragment/. - smiles_canonical: SMILES canónico - molecule_id: ID de la molécula - bonds: Lista de enlaces evaluados - smiles_list: Lista de SMILES (opcional) - xyz_block: Cadena XYZ (opcional)
 */
export interface FragmentResponseData { 
    smiles_canonical: string;
    molecule_id: string;
    bonds: Array<EvaluatedFragmentBond>;
    smiles_list?: Array<string> | null;
    xyz_block?: string | null;
}

